# 使用本地编译的超简单Dockerfile  
FROM ubuntu:22.04

# 更新包管理器并安装基础工具（可选）
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制本地编译好的二进制文件
COPY main .
COPY web ./web
# COPY sample_config.yaml .

# 设置main文件为可执行
RUN chmod +x main

# 暴露端口
EXPOSE 8080

# 直接运行
CMD ["./main"]
